const resolve = require('@rollup/plugin-node-resolve');
const typescript = require('@rollup/plugin-typescript');
const dts = require('rollup-plugin-dts').default;
const packageJson = require('./package.json');

module.exports = [
  // 1. The JavaScript Build
  {
    input: 'src/index.ts', // Where your code starts
    output: [
      {
        file: packageJson.main, // Output for older tools (CommonJS)
        format: 'cjs',
        sourcemap: true,
      },
      {
        file: packageJson.module, // Output for modern tools (ES Modules)
        format: 'esm',
        sourcemap: true,
      },
    ],
    // Plugins needed to understand your code
    plugins: [
      resolve(), // Helps find external modules
      typescript({ tsconfig: './tsconfig.json' }), // Converts TS to JS
    ],
    // Important: Don't bundle React! Let the user provide it.
    external: ['react', 'react-dom'], 
  },
  
  // 2. The Type Definitions Build (.d.ts)
  {
    input: 'dist/index.d.ts', // Takes the raw types generated by step 1
    output: [{ file: 'dist/index.d.ts', format: 'esm' }], // Bundles them into one file
    plugins: [dts()],
  },
];